### ISSUE TITLE
java.util.zip.ZipException

### ISSUE THREAD

**Issue by 1fabiopereira** [In-Loco-Media/react-native-inlocoengage#1]
I'm trying to use react-native-inlocomedia in version ^ 2.0.0 and react-native-inlocoengage in version ^ 2.0.0 and how much do I try to compile for Android I get the following error:

```Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/inlocomedia/reactnative/BuildConfig.class

**Comment by pedroatanasio** [comment]
Hi, @1fabiopereira! Thank you for reporting the issue.

This problem happened because both media and engage plugins had the same package name. Both libraries were generating BuildConfig classes in the same package and thus the error message. 

The issue was fixed on version **3.0.1**  of both plugins and you should upgrade to this version.

I would recommend unlinking the old plugin versions with `react-native unlink react-native-inlocomedia` and `react-native unlink react-native-inlocoengage` before installing the new ones since the package names changed.

Thank you!
